import React, { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';

// Storage key for language preference
const LANGUAGE_STORAGE_KEY = 'thundra_language_preference';

// Helper functions for persistent storage
const saveLanguagePreference = (lang: string) => {
  try {
    // Save to localStorage
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    // Save to cookie (expires in 1 year)
    document.cookie = `${LANGUAGE_STORAGE_KEY}=${lang};path=/;max-age=31536000;SameSite=Lax`;
  } catch (e) {
    console.warn('Could not save language preference:', e);
  }
};

const getStoredLanguagePreference = (): string | null => {
  try {
    // Try localStorage first
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored) return stored;
    // Fallback to cookie
    const cookies = document.cookie.split(';');
    for (const cookie of cookies) {
      const [key, value] = cookie.trim().split('=');
      if (key === LANGUAGE_STORAGE_KEY) return value;
    }
  } catch (e) {
    console.warn('Could not read language preference:', e);
  }
  return null;
};

// Re-export languages for external use

export type LanguageCode = 
  | 'en' | 'fr' | 'sw' | 'swc' | 'es' | 'zh' | 'ja' | 'nl' | 'de' | 'it' 
  | 'pt' | 'ar' | 'rw' | 'ln' | 'rn' | 'yo' | 'zu' | 'wo' | 'ro' | 'ru' 
  | 'lg' | 'uk' | 'tl' | 'vi' | 'hi' | 'tr' | 'hr' | 'sr' | 'da' | 'sv' 
  | 'no' | 'fi' | 'ko';

export interface Language {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'sw', name: 'Swahili (Tanzania)', nativeName: 'Swahili', flag: '🇹🇿' },
  { code: 'swc', name: 'Kiswahili (DR Congo)', nativeName: 'Kiswahili ya Congo', flag: '🇨🇩' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', flag: '🇷🇼' },
  { code: 'ln', name: 'Lingala', nativeName: 'Lingála', flag: '🇨🇩' },
  { code: 'rn', name: 'Kirundi', nativeName: 'Ikirundi', flag: '🇧🇮' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', flag: '🇳🇬' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', flag: '🇿🇦' },
  { code: 'wo', name: 'Wolof', nativeName: 'Wolof', flag: '🇸🇳' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'lg', name: 'Luganda', nativeName: 'Luganda', flag: '🇺🇬' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'tl', name: 'Filipino', nativeName: 'Filipino', flag: '🇵🇭' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', flag: '🇭🇷' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', flag: '🇷🇸' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', flag: '🇩🇰' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', flag: '🇳🇴' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', flag: '🇫🇮' },
];

// Footer translation keys (required for full translation)
export interface FooterTranslations {
  tagline: string;
  company: string;
  resources: string;
  legal: string;
  social: string;
  copyright: string;
  quickLinks: string;
  aboutUs: string;
  learnMore: string;
  whitepaper: string;
  privacyPolicy: string;
  termsOfService: string;
  contact: string;
}

// Translation keys for the app
export interface Translations {
  // Navigation
  nav: {
    home: string;
    discover: string;
    artists: string;
    marketplace: string;
    community: string;
    business: string;
    login: string;
    signup: string;
    getStarted: string;
  };
  // Hero section
  hero: {
    title: string;
    titleHighlight: string;
    subtitle: string;
    cta: string;
    secondaryCta: string;
    stats: {
      artists: string;
      royalties: string;
      fans: string;
      burned: string;
    };
  };
  // Features
  features: {
    title: string;
    subtitle: string;
    streaming: { title: string; description: string };
    social: { title: string; description: string };
    marketplace: { title: string; description: string };
    ai: { title: string; description: string };
    governance: { title: string; description: string };
    wallet: { title: string; description: string };
  };
  // Tokenomics
  tokenomics: {
    title: string;
    subtitle: string;
    artistRoyalties: string;
    fanRewards: string;
    platform: string;
    burning: string;
  };
  // Footer
  footer: FooterTranslations;
  // Common
  common: {
    learnMore: string;
    comingSoon: string;
    joinWaitlist: string;
    darkMode: string;
    lightMode: string;
    language: string;
  };
  // Dashboard
  dashboard?: {
    home: string;
    search: string;
    music: string;
    library: string;
    favorites: string;
    leaderboard: string;
    profile: string;
    wallet: string;
    chat: string;
    learning: string;
    market: string;
    ai: string;
    ads: string;
    artist: string;
    moderator: string;
    admin: string;
    settings: string;
    logout: string;
    upload: string;
    earnings: string;
    followers: string;
    streams: string;
    likes: string;
  };
}

// Internal translation type that allows partial footer
interface PartialTranslations extends Omit<Translations, 'footer'> {
  footer: Partial<FooterTranslations>;
}

// Base English translations
const enTranslations: Translations = {
  nav: {
    home: 'Home',
    discover: 'Discover',
    artists: 'For Artists',
    marketplace: 'For Business',
    community: 'For Community',
    business: 'For Business',
    login: 'Log In',
    signup: 'Sign Up',
    getStarted: 'Get Started',
  },
  hero: {
    title: 'The Future of',
    titleHighlight: 'Music is Decentralized',
    subtitle: 'Stream, earn, and own your music. Thundra Music empowers artists with 65% royalties and rewards fans for every interaction.',
    cta: 'Start Listening',
    secondaryCta: 'Learn More',
    stats: {
      artists: 'Artist Royalties',
      royalties: 'Higher than Spotify',
      fans: 'Active Fans',
      burned: '$THDR Burned',
    },
  },
  features: {
    title: 'Everything Music Should Be',
    subtitle: 'A complete ecosystem for artists, fans, and creators',
    streaming: { title: 'Paid Streaming', description: 'Earn $THDR tokens for every stream. Artists get 65% royalties instantly.' },
    social: { title: 'Social Spaces', description: 'Feed, chats, channels, and audio spaces. Connect with your community.' },
    marketplace: { title: 'NFT Marketplace', description: 'Music NFTs, concert tickets, exclusive merch, and collectibles.' },
    ai: { title: 'AI Creative Tools', description: 'Generate music, lyrics, and video clips with cutting-edge AI.' },
    governance: { title: 'Community Governance', description: 'Vote on features, artist promotions, and platform decisions.' },
    wallet: { title: 'Integrated Wallet', description: 'Custodial to non-custodial. Store $THDR, stablecoins, and NFTs.' },
  },
  tokenomics: {
    title: '$THDR Tokenomics',
    subtitle: 'Fair distribution. Deflationary by design.',
    artistRoyalties: 'Artist Royalties',
    fanRewards: 'Fan Rewards',
    platform: 'Platform',
    burning: '100% Fees Burned',
  },
  footer: {
    tagline: 'The Decentralized Music Infrastructure For The Future.',
    company: 'Company',
    resources: 'Resources',
    legal: 'Legal',
    social: 'Social',
    copyright: '© 2026 Thundra Music Inc. All rights reserved.',
    quickLinks: 'Quick Links',
    aboutUs: 'About Us',
    learnMore: 'Learn More',
    whitepaper: 'Whitepaper',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    contact: 'Contact',
  },
  common: {
    learnMore: 'Learn More',
    comingSoon: 'Coming Soon',
    joinWaitlist: 'Join Waitlist',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
  },
  dashboard: {
    home: 'Home',
    search: 'Search',
    music: 'Music',
    library: 'Library',
    favorites: 'Favorites',
    leaderboard: 'Leaderboard',
    profile: 'Profile',
    wallet: 'Wallet',
    chat: 'Chat Space',
    learning: 'Learning',
    market: 'Market',
    ai: 'Thundra AI',
    ads: 'Ads',
    artist: 'Artist Studio',
    moderator: 'Mod Panel',
    admin: 'Admin Panel',
    settings: 'Settings',
    logout: 'Log Out',
    upload: 'Upload Track',
    earnings: 'Earnings',
    followers: 'Followers',
    streams: 'Streams',
    likes: 'Likes',
  },
};

const translations: Record<LanguageCode, PartialTranslations> = {
  en: enTranslations,
  fr: {
    nav: { home: 'Accueil', discover: 'Découvrir', artists: 'Pour Artistes', marketplace: 'Pour Entreprises', community: 'Pour Communauté', business: 'Pour Entreprises', login: 'Connexion', signup: 'Inscription', getStarted: 'Commencer' },
    hero: { title: "L'Avenir de la", titleHighlight: 'Musique est Décentralisé', subtitle: 'Streamez, gagnez et possédez votre musique. Thundra Music offre 65% de royalties aux artistes et récompense les fans.', cta: 'Commencer à Écouter', secondaryCta: 'En Savoir Plus', stats: { artists: 'Royalties Artistes', royalties: 'Plus que Spotify', fans: 'Fans Actifs', burned: '$THDR Brûlés' } },
    features: { title: 'Tout ce que la Musique Devrait Être', subtitle: 'Un écosystème complet pour artistes, fans et créateurs', streaming: { title: 'Streaming Rémunéré', description: 'Gagnez des tokens $THDR pour chaque écoute. 65% de royalties instantanées.' }, social: { title: 'Espaces Sociaux', description: 'Feed, chats, chaînes et espaces audio. Connectez-vous à votre communauté.' }, marketplace: { title: 'Marketplace NFT', description: 'NFTs musicaux, billets de concert, merch exclusif et collectibles.' }, ai: { title: 'Outils IA Créatifs', description: 'Générez musique, paroles et clips vidéo avec une IA avancée.' }, governance: { title: 'Gouvernance Communautaire', description: 'Votez sur les fonctionnalités et les décisions de la plateforme.' }, wallet: { title: 'Portefeuille Intégré', description: 'Custodial à non-custodial. Stockez $THDR, stablecoins et NFTs.' } },
    tokenomics: { title: 'Tokenomics $THDR', subtitle: 'Distribution équitable. Déflationniste par design.', artistRoyalties: 'Royalties Artistes', fanRewards: 'Récompenses Fans', platform: 'Plateforme', burning: '100% Frais Brûlés' },
    footer: { tagline: "L'Infrastructure Musicale Décentralisée Pour L'Avenir.", company: 'Entreprise', resources: 'Ressources', legal: 'Légal', social: 'Social', copyright: '© 2026 Thundra Music Inc. Tous droits réservés.', quickLinks: 'Liens Rapides', aboutUs: 'À Propos', learnMore: 'En Savoir Plus', whitepaper: 'Livre Blanc', privacyPolicy: 'Politique de Confidentialité', termsOfService: 'Conditions d\'Utilisation', contact: 'Contact' },
    common: { learnMore: 'En Savoir Plus', comingSoon: 'Bientôt Disponible', joinWaitlist: 'Rejoindre la Liste', darkMode: 'Mode Sombre', lightMode: 'Mode Clair', language: 'Langue' },
    dashboard: { home: 'Accueil', search: 'Rechercher', music: 'Musique', library: 'Bibliothèque', favorites: 'Favoris', leaderboard: 'Classement', profile: 'Profil', wallet: 'Portefeuille', chat: 'Espace Chat', learning: 'Apprentissage', market: 'Marché', ai: 'Thundra IA', ads: 'Publicités', artist: 'Studio Artiste', moderator: 'Panel Mod', admin: 'Panel Admin', settings: 'Paramètres', logout: 'Déconnexion', upload: 'Télécharger', earnings: 'Revenus', followers: 'Abonnés', streams: 'Écoutes', likes: 'J\'aimes' },
  },
  sw: {
    nav: { home: 'Nyumbani', discover: 'Gundua', artists: 'Kwa Wasanii', marketplace: 'Kwa Biashara', community: 'Kwa Jamii', business: 'Kwa Biashara', login: 'Ingia', signup: 'Jisajili', getStarted: 'Anza' },
    hero: { title: 'Mustakabali wa', titleHighlight: 'Muziki ni wa Uhuru', subtitle: 'Sikiliza, pata, na miliki muziki wako. Thundra Music inawapa wasanii 65% ya mrabaha na kuwazawadia mashabiki.', cta: 'Anza Kusikiliza', secondaryCta: 'Jifunze Zaidi', stats: { artists: 'Mrabaha wa Wasanii', royalties: 'Zaidi ya Spotify', fans: 'Mashabiki Hai', burned: '$THDR Zilizochomwa' } },
    features: { title: 'Kila Kitu Muziki Unapaswa Kuwa', subtitle: 'Mfumo kamili kwa wasanii, mashabiki, na wabunifu', streaming: { title: 'Kusikiliza kwa Malipo', description: 'Pata tokeni za $THDR kwa kila kusikiliza. Wasanii wanapata 65% mara moja.' }, social: { title: 'Nafasi za Kijamii', description: 'Feed, mazungumzo, na nafasi za sauti. Ungana na jamii yako.' }, marketplace: { title: 'Soko la NFT', description: 'NFT za muziki, tiketi za tamasha, na bidhaa za kipekee.' }, ai: { title: 'Zana za AI', description: 'Tengeneza muziki, maneno, na video na AI ya hali ya juu.' }, governance: { title: 'Utawala wa Jamii', description: 'Piga kura juu ya vipengele na maamuzi ya jukwaa.' }, wallet: { title: 'Mkoba Uliounganishwa', description: 'Hifadhi $THDR, stablecoins, na NFT.' } },
    tokenomics: { title: 'Tokenomics ya $THDR', subtitle: 'Usambazaji wa haki. Deflation kwa muundo.', artistRoyalties: 'Mrabaha wa Wasanii', fanRewards: 'Zawadi za Mashabiki', platform: 'Jukwaa', burning: '100% Ada Zinachomwa' },
    footer: { tagline: 'Miundombinu ya Muziki Iliyogatuliwa Kwa Mustakabali.', company: 'Kampuni', resources: 'Rasilimali', legal: 'Kisheria', social: 'Kijamii', copyright: '© 2026 Thundra Music Inc. Haki zote zimehifadhiwa.', quickLinks: 'Viungo vya Haraka', aboutUs: 'Kuhusu Sisi', learnMore: 'Jifunze Zaidi', whitepaper: 'Waraka Mweupe', privacyPolicy: 'Sera ya Faragha', termsOfService: 'Masharti ya Huduma', contact: 'Wasiliana Nasi' },
    common: { learnMore: 'Jifunze Zaidi', comingSoon: 'Inakuja Hivi Karibuni', joinWaitlist: 'Jiunge na Orodha', darkMode: 'Hali ya Giza', lightMode: 'Hali ya Mwanga', language: 'Lugha' },
    dashboard: { home: 'Nyumbani', search: 'Tafuta', music: 'Muziki', library: 'Maktaba', favorites: 'Vipendwa', leaderboard: 'Orodha ya Bora', profile: 'Wasifu', wallet: 'Mkoba', chat: 'Sehemu ya Mazungumzo', learning: 'Kujifunza', market: 'Soko', ai: 'Thundra AI', ads: 'Matangazo', artist: 'Studio ya Msanii', moderator: 'Paneli ya Msimamizi', admin: 'Paneli ya Admin', settings: 'Mipangilio', logout: 'Toka', upload: 'Pakia Wimbo', earnings: 'Mapato', followers: 'Wafuasi', streams: 'Sikilizo', likes: 'Kupenda' },
  },
  swc: {
    nav: { home: 'Nyumba', discover: 'Tafuta', artists: 'Kwa Artistes', marketplace: 'Kwa Biznes', community: 'Kwa Jamaa', business: 'Kwa Biznes', login: 'Kuingia', signup: 'Kujiandikisha', getStarted: 'Anza Sasa' },
    hero: { title: 'Kesho ya', titleHighlight: 'Muziki ni Uhuru', subtitle: 'Sikiliza, pata pesa, na miliki muziki yako. Thundra inapea artistes 65% ya pesa na zawadi kwa mashabiki.', cta: 'Anza Kusikiliza', secondaryCta: 'Jua Zaidi', stats: { artists: 'Pesa ya Artistes', royalties: 'Kuliko Spotify', fans: 'Mashabiki', burned: '$THDR Zimeunguzwa' } },
    features: { title: 'Muziki Kamili', subtitle: 'Programu moja kwa artistes, mashabiki, na wabunifu', streaming: { title: 'Kusikiliza na Kupata Pesa', description: 'Pata $THDR kwa kila wimbo unasikiliza.' }, social: { title: 'Sehemu ya Kuongea', description: 'Feed, chat, na sauti. Kuwa na jamaa yako.' }, marketplace: { title: 'Duka la NFT', description: 'NFT za muziki, tiketi, na vitu.' }, ai: { title: 'AI Tools', description: 'Tengeneza muziki na AI.' }, governance: { title: 'Utawala wa Jamaa', description: 'Chagua maamuzi.' }, wallet: { title: 'Mkoba', description: 'Weka $THDR na NFT.' } },
    tokenomics: { title: 'Tokenomics', subtitle: 'Ugawanyaji mzuri.', artistRoyalties: 'Pesa ya Artistes', fanRewards: 'Zawadi', platform: 'Programu', burning: 'Ada Zinaunguzwa' },
    footer: { tagline: 'Miundombinu ya Muziki Iliyogatuliwa Kwa Kesho.', company: 'Kampani', resources: 'Rasilimali', legal: 'Sheria', social: 'Jamaa', copyright: '© 2026 Thundra Music Inc. Haki zote zimehifadhiwa.', quickLinks: 'Viungo vya Haraka' },
    common: { learnMore: 'Jua Zaidi', comingSoon: 'Inakuja', joinWaitlist: 'Jiunge', darkMode: 'Giza', lightMode: 'Mwangaza', language: 'Lugha' },
    dashboard: { home: 'Nyumba', search: 'Tafuta', music: 'Muziki', library: 'Biblioteki', favorites: 'Vipendwa', leaderboard: 'Orodha Bora', profile: 'Profil', wallet: 'Mkoba', chat: 'Mazungumzo', learning: 'Kujifunza', market: 'Duka', ai: 'Thundra AI', ads: 'Pub', artist: 'Studio Artiste', moderator: 'Panel Mod', admin: 'Panel Admin', settings: 'Reglages', logout: 'Kuondoka', upload: 'Tia Wimbo', earnings: 'Pesa', followers: 'Wafuasi', streams: 'Kusikiliza', likes: 'Kupenda' },
  },
  es: { nav: { home: 'Inicio', discover: 'Descubrir', artists: 'Para Artistas', marketplace: 'Para Empresas', community: 'Para Comunidad', business: 'Para Empresas', login: 'Iniciar Sesión', signup: 'Registrarse', getStarted: 'Comenzar' }, hero: { title: 'El Futuro de la', titleHighlight: 'Música es Descentralizado', subtitle: 'Transmite, gana y sé dueño de tu música. Thundra Music ofrece 65% de regalías a los artistas.', cta: 'Empezar a Escuchar', secondaryCta: 'Más Información', stats: { artists: 'Regalías de Artistas', royalties: 'Más que Spotify', fans: 'Fans Activos', burned: '$THDR Quemados' } }, features: { title: 'Todo lo que la Música Debería Ser', subtitle: 'Un ecosistema completo para artistas, fans y creadores', streaming: { title: 'Streaming Pagado', description: 'Gana tokens $THDR por cada reproducción.' }, social: { title: 'Espacios Sociales', description: 'Feed, chats y espacios de audio.' }, marketplace: { title: 'Mercado NFT', description: 'NFTs de música, entradas y merchandising.' }, ai: { title: 'Herramientas IA', description: 'Genera música y letras con IA.' }, governance: { title: 'Gobernanza', description: 'Vota en decisiones de la plataforma.' }, wallet: { title: 'Billetera', description: 'Almacena $THDR y NFTs.' } }, tokenomics: { title: 'Tokenomics $THDR', subtitle: 'Distribución justa. Deflacionario por diseño.', artistRoyalties: 'Regalías', fanRewards: 'Recompensas', platform: 'Plataforma', burning: '100% Comisiones Quemadas' }, footer: { tagline: 'La Infraestructura Musical Descentralizada Para El Futuro.', company: 'Empresa', resources: 'Recursos', legal: 'Legal', social: 'Social', copyright: '© 2026 Thundra Music Inc. Todos los derechos reservados.', quickLinks: 'Enlaces Rápidos' }, common: { learnMore: 'Más Info', comingSoon: 'Próximamente', joinWaitlist: 'Unirse', darkMode: 'Modo Oscuro', lightMode: 'Modo Claro', language: 'Idioma' }, dashboard: { home: 'Inicio', search: 'Buscar', music: 'Música', library: 'Biblioteca', favorites: 'Favoritos', leaderboard: 'Clasificación', profile: 'Perfil', wallet: 'Billetera', chat: 'Chat', learning: 'Aprendizaje', market: 'Mercado', ai: 'Thundra IA', ads: 'Anuncios', artist: 'Estudio Artista', moderator: 'Panel Mod', admin: 'Panel Admin', settings: 'Ajustes', logout: 'Cerrar Sesión', upload: 'Subir', earnings: 'Ganancias', followers: 'Seguidores', streams: 'Reproducciones', likes: 'Me gusta' } },
  zh: { nav: { home: '首页', discover: '发现', artists: '艺术家专区', marketplace: '企业专区', community: '社区专区', business: '企业专区', login: '登录', signup: '注册', getStarted: '开始' }, hero: { title: '音乐的未来是', titleHighlight: '去中心化的', subtitle: '流媒体、赚取并拥有您的音乐。Thundra Music为艺术家提供65%的版税。', cta: '开始收听', secondaryCta: '了解更多', stats: { artists: '艺术家版税', royalties: '高于Spotify', fans: '活跃粉丝', burned: '$THDR已销毁' } }, features: { title: '音乐应有的一切', subtitle: '为艺术家、粉丝和创作者打造的完整生态系统', streaming: { title: '付费流媒体', description: '每次播放获得$THDR代币。' }, social: { title: '社交空间', description: '动态、聊天和音频空间。' }, marketplace: { title: 'NFT市场', description: '音乐NFT、门票和商品。' }, ai: { title: 'AI工具', description: '用AI生成音乐和歌词。' }, governance: { title: '社区治理', description: '为平台决策投票。' }, wallet: { title: '钱包', description: '存储$THDR和NFT。' } }, tokenomics: { title: '$THDR代币经济', subtitle: '公平分配。通缩设计。', artistRoyalties: '艺术家版税', fanRewards: '粉丝奖励', platform: '平台', burning: '100%费用销毁' }, footer: { tagline: '未来的去中心化音乐基础设施。', company: '公司', resources: '资源', legal: '法律', social: '社交', copyright: '© 2026 Thundra Music Inc. 保留所有权利。', quickLinks: '快速链接' }, common: { learnMore: '了解更多', comingSoon: '即将推出', joinWaitlist: '加入等候名单', darkMode: '深色模式', lightMode: '浅色模式', language: '语言' }, dashboard: { home: '首页', search: '搜索', music: '音乐', library: '音乐库', favorites: '收藏', leaderboard: '排行榜', profile: '个人资料', wallet: '钱包', chat: '聊天', learning: '学习', market: '市场', ai: 'AI助手', ads: '广告', artist: '艺术家工作室', moderator: '管理面板', admin: '管理员面板', settings: '设置', logout: '退出', upload: '上传', earnings: '收入', followers: '粉丝', streams: '播放', likes: '点赞' } },
  ja: { nav: { home: 'ホーム', discover: '発見', artists: 'アーティスト向け', marketplace: 'ビジネス向け', community: 'コミュニティ向け', business: 'ビジネス向け', login: 'ログイン', signup: '登録', getStarted: '始める' }, hero: { title: '音楽の未来は', titleHighlight: '分散型である', subtitle: 'ストリーミング、稼ぐ、音楽を所有。Thundra Musicはアーティストに65%のロイヤリティを提供。', cta: '聴き始める', secondaryCta: '詳細', stats: { artists: 'ロイヤリティ', royalties: 'Spotifyより高い', fans: 'アクティブファン', burned: '$THDR焼却' } }, features: { title: '音楽のあるべき姿', subtitle: 'アーティスト、ファン、クリエイターのための完全なエコシステム', streaming: { title: '有料ストリーミング', description: '再生ごとに$THDRトークンを獲得。' }, social: { title: 'ソーシャルスペース', description: 'フィード、チャット、オーディオスペース。' }, marketplace: { title: 'NFTマーケット', description: '音楽NFT、チケット、グッズ。' }, ai: { title: 'AIツール', description: 'AIで音楽と歌詞を生成。' }, governance: { title: 'ガバナンス', description: 'プラットフォームの決定に投票。' }, wallet: { title: 'ウォレット', description: '$THDRとNFTを保存。' } }, tokenomics: { title: '$THDRトケノミクス', subtitle: '公平な分配。デフレ設計。', artistRoyalties: 'ロイヤリティ', fanRewards: 'ファン報酬', platform: 'プラットフォーム', burning: '100%手数料焼却' }, footer: { tagline: '未来の分散型音楽インフラストラクチャ。', company: '会社', resources: 'リソース', legal: '法的', social: 'ソーシャル', copyright: '© 2026 Thundra Music Inc. 全著作権所有。', quickLinks: 'クイックリンク' }, common: { learnMore: '詳細', comingSoon: '近日公開', joinWaitlist: '参加', darkMode: 'ダークモード', lightMode: 'ライトモード', language: '言語' }, dashboard: { home: 'ホーム', search: '検索', music: '音楽', library: 'ライブラリ', favorites: 'お気に入り', leaderboard: 'ランキング', profile: 'プロフィール', wallet: 'ウォレット', chat: 'チャット', learning: '学習', market: 'マーケット', ai: 'AI', ads: '広告', artist: 'スタジオ', moderator: 'モデレーター', admin: '管理者', settings: '設定', logout: 'ログアウト', upload: 'アップロード', earnings: '収益', followers: 'フォロワー', streams: '再生数', likes: 'いいね' } },
  ko: { nav: { home: '홈', discover: '발견', artists: '아티스트용', marketplace: '비즈니스용', community: '커뮤니티용', business: '비즈니스용', login: '로그인', signup: '회원가입', getStarted: '시작하기' }, hero: { title: '음악의 미래는', titleHighlight: '탈중앙화', subtitle: '스트리밍하고, 수익을 얻고, 음악을 소유하세요. Thundra Music은 아티스트에게 65%의 로열티를 제공합니다.', cta: '듣기 시작', secondaryCta: '더 알아보기', stats: { artists: '아티스트 로열티', royalties: 'Spotify보다 높은', fans: '활성 팬', burned: '$THDR 소각' } }, features: { title: '음악이 되어야 할 모든 것', subtitle: '아티스트, 팬, 크리에이터를 위한 완전한 생태계', streaming: { title: '유료 스트리밍', description: '스트림당 $THDR 토큰을 획득하세요.' }, social: { title: '소셜 스페이스', description: '피드, 채팅, 오디오 스페이스.' }, marketplace: { title: 'NFT 마켓', description: '음악 NFT, 티켓, 굿즈.' }, ai: { title: 'AI 도구', description: 'AI로 음악과 가사를 생성.' }, governance: { title: '거버넌스', description: '플랫폼 결정에 투표.' }, wallet: { title: '지갑', description: '$THDR과 NFT 저장.' } }, tokenomics: { title: '$THDR 토크노믹스', subtitle: '공정한 분배. 디플레이션 설계.', artistRoyalties: '로열티', fanRewards: '팬 보상', platform: '플랫폼', burning: '100% 수수료 소각' }, footer: { tagline: '미래를 위한 탈중앙화 음악 인프라.', company: '회사', resources: '리소스', legal: '법적', social: '소셜', copyright: '© 2026 Thundra Music Inc. 모든 권리 보유.', quickLinks: '빠른 링크' }, common: { learnMore: '더 보기', comingSoon: '곧 출시', joinWaitlist: '대기자 명단', darkMode: '다크 모드', lightMode: '라이트 모드', language: '언어' }, dashboard: { home: '홈', search: '검색', music: '음악', library: '라이브러리', favorites: '즐겨찾기', leaderboard: '리더보드', profile: '프로필', wallet: '지갑', chat: '채팅', learning: '학습', market: '마켓', ai: 'AI', ads: '광고', artist: '스튜디오', moderator: '모더레이터', admin: '관리자', settings: '설정', logout: '로그아웃', upload: '업로드', earnings: '수익', followers: '팔로워', streams: '스트림', likes: '좋아요' } },
  nl: { nav: { home: 'Home', discover: 'Ontdek', artists: 'Voor Artiesten', marketplace: 'Voor Bedrijven', community: 'Voor Gemeenschap', business: 'Voor Bedrijven', login: 'Inloggen', signup: 'Aanmelden', getStarted: 'Beginnen' }, hero: { title: 'De Toekomst van', titleHighlight: 'Muziek is Gedecentraliseerd', subtitle: 'Stream, verdien en bezit je muziek. Thundra Music geeft artiesten 65% royalties.', cta: 'Begin met Luisteren', secondaryCta: 'Meer Info', stats: { artists: 'Artiest Royalties', royalties: 'Hoger dan Spotify', fans: 'Actieve Fans', burned: '$THDR Verbrand' } }, features: { title: 'Alles wat Muziek Zou Moeten Zijn', subtitle: 'Een compleet ecosysteem voor artiesten, fans en creators', streaming: { title: 'Betaald Streamen', description: 'Verdien $THDR tokens per stream.' }, social: { title: 'Sociale Ruimtes', description: 'Feed, chats en audio spaces.' }, marketplace: { title: 'NFT Marktplaats', description: 'Muziek NFTs, tickets en merchandise.' }, ai: { title: 'AI Tools', description: 'Genereer muziek met AI.' }, governance: { title: 'Governance', description: 'Stem over platformbeslissingen.' }, wallet: { title: 'Portemonnee', description: 'Bewaar $THDR en NFTs.' } }, tokenomics: { title: '$THDR Tokenomics', subtitle: 'Eerlijke verdeling. Deflatoir ontwerp.', artistRoyalties: 'Royalties', fanRewards: 'Beloningen', platform: 'Platform', burning: '100% Fees Verbrand' }, footer: { tagline: 'Gedecentraliseerde Muziekinfrastructuur Voor De Toekomst.', company: 'Bedrijf', resources: 'Bronnen', legal: 'Juridisch', social: 'Sociaal', copyright: '© 2026 Thundra Music Inc. Alle rechten voorbehouden.', quickLinks: 'Snelle Links' }, common: { learnMore: 'Meer Info', comingSoon: 'Binnenkort', joinWaitlist: 'Aanmelden', darkMode: 'Donkere Modus', lightMode: 'Lichte Modus', language: 'Taal' }, dashboard: { home: 'Home', search: 'Zoeken', music: 'Muziek', library: 'Bibliotheek', favorites: 'Favorieten', leaderboard: 'Ranglijst', profile: 'Profiel', wallet: 'Portemonnee', chat: 'Chat', learning: 'Leren', market: 'Markt', ai: 'AI', ads: 'Advertenties', artist: 'Studio', moderator: 'Moderator', admin: 'Admin', settings: 'Instellingen', logout: 'Uitloggen', upload: 'Uploaden', earnings: 'Inkomsten', followers: 'Volgers', streams: 'Streams', likes: 'Likes' } },
  de: { nav: { home: 'Startseite', discover: 'Entdecken', artists: 'Für Künstler', marketplace: 'Für Unternehmen', community: 'Für Community', business: 'Für Unternehmen', login: 'Anmelden', signup: 'Registrieren', getStarted: 'Loslegen' }, hero: { title: 'Die Zukunft der', titleHighlight: 'Musik ist Dezentral', subtitle: 'Streame, verdiene und besitze deine Musik. Thundra Music bietet Künstlern 65% Tantiemen.', cta: 'Jetzt Anhören', secondaryCta: 'Mehr Erfahren', stats: { artists: 'Künstler-Tantiemen', royalties: 'Höher als Spotify', fans: 'Aktive Fans', burned: '$THDR Verbrannt' } }, features: { title: 'Alles was Musik sein sollte', subtitle: 'Ein komplettes Ökosystem für Künstler, Fans und Creator', streaming: { title: 'Bezahltes Streaming', description: 'Verdiene $THDR Tokens pro Stream.' }, social: { title: 'Soziale Räume', description: 'Feed, Chats und Audio Spaces.' }, marketplace: { title: 'NFT Marktplatz', description: 'Musik NFTs, Tickets und Merchandise.' }, ai: { title: 'KI-Tools', description: 'Generiere Musik mit KI.' }, governance: { title: 'Governance', description: 'Stimme über Plattform-Entscheidungen ab.' }, wallet: { title: 'Wallet', description: 'Speichere $THDR und NFTs.' } }, tokenomics: { title: '$THDR Tokenomics', subtitle: 'Faire Verteilung. Deflationär by Design.', artistRoyalties: 'Tantiemen', fanRewards: 'Fan-Belohnungen', platform: 'Plattform', burning: '100% Gebühren verbrannt' }, footer: { tagline: 'Die Dezentrale Musikinfrastruktur Für Die Zukunft.', company: 'Unternehmen', resources: 'Ressourcen', legal: 'Rechtliches', social: 'Soziales', copyright: '© 2026 Thundra Music Inc. Alle Rechte vorbehalten.', quickLinks: 'Schnellzugriff' }, common: { learnMore: 'Mehr Erfahren', comingSoon: 'Demnächst', joinWaitlist: 'Warteliste', darkMode: 'Dunkelmodus', lightMode: 'Hellmodus', language: 'Sprache' }, dashboard: { home: 'Home', search: 'Suchen', music: 'Musik', library: 'Bibliothek', favorites: 'Favoriten', leaderboard: 'Rangliste', profile: 'Profil', wallet: 'Wallet', chat: 'Chat', learning: 'Lernen', market: 'Markt', ai: 'KI', ads: 'Werbung', artist: 'Studio', moderator: 'Moderator', admin: 'Admin', settings: 'Einstellungen', logout: 'Abmelden', upload: 'Hochladen', earnings: 'Einnahmen', followers: 'Follower', streams: 'Streams', likes: 'Likes' } },
  it: { nav: { home: 'Home', discover: 'Scopri', artists: 'Per Artisti', marketplace: 'Per Aziende', community: 'Per la Comunità', business: 'Per Aziende', login: 'Accedi', signup: 'Registrati', getStarted: 'Inizia' }, hero: { title: 'Il Futuro della', titleHighlight: 'Musica è Decentralizzato', subtitle: 'Ascolta, guadagna e possiedi la tua musica. Thundra Music offre il 65% di royalties agli artisti.', cta: 'Inizia ad Ascoltare', secondaryCta: 'Scopri di Più', stats: { artists: 'Royalties Artisti', royalties: 'Più di Spotify', fans: 'Fan Attivi', burned: '$THDR Bruciati' } }, features: { title: 'Tutto Ciò che la Musica Dovrebbe Essere', subtitle: 'Un ecosistema completo per artisti, fan e creatori', streaming: { title: 'Streaming a Pagamento', description: 'Guadagna token $THDR per ogni stream.' }, social: { title: 'Spazi Sociali', description: 'Feed, chat e spazi audio.' }, marketplace: { title: 'Mercato NFT', description: 'NFT musicali, biglietti e merchandise.' }, ai: { title: 'Strumenti AI', description: 'Genera musica con AI.' }, governance: { title: 'Governance', description: 'Vota sulle decisioni della piattaforma.' }, wallet: { title: 'Portafoglio', description: 'Conserva $THDR e NFT.' } }, tokenomics: { title: 'Tokenomics $THDR', subtitle: 'Distribuzione equa. Deflazionario per design.', artistRoyalties: 'Royalties', fanRewards: 'Premi Fan', platform: 'Piattaforma', burning: '100% Fee Bruciate' }, footer: { tagline: "L'Infrastruttura Musicale Decentralizzata Per Il Futuro.", company: 'Azienda', resources: 'Risorse', legal: 'Legale', social: 'Social', copyright: '© 2026 Thundra Music Inc. Tutti i diritti riservati.', quickLinks: 'Link Rapidi' }, common: { learnMore: 'Scopri', comingSoon: 'Prossimamente', joinWaitlist: 'Iscriviti', darkMode: 'Modalità Scura', lightMode: 'Modalità Chiara', language: 'Lingua' }, dashboard: { home: 'Home', search: 'Cerca', music: 'Musica', library: 'Libreria', favorites: 'Preferiti', leaderboard: 'Classifica', profile: 'Profilo', wallet: 'Portafoglio', chat: 'Chat', learning: 'Apprendimento', market: 'Mercato', ai: 'IA', ads: 'Pubblicità', artist: 'Studio', moderator: 'Moderatore', admin: 'Admin', settings: 'Impostazioni', logout: 'Esci', upload: 'Carica', earnings: 'Guadagni', followers: 'Follower', streams: 'Stream', likes: 'Mi piace' } },
  pt: { nav: { home: 'Início', discover: 'Descobrir', artists: 'Para Artistas', marketplace: 'Para Empresas', community: 'Para Comunidade', business: 'Para Empresas', login: 'Entrar', signup: 'Cadastrar', getStarted: 'Começar' }, hero: { title: 'O Futuro da', titleHighlight: 'Música é Descentralizado', subtitle: 'Transmita, ganhe e seja dono da sua música. Thundra Music oferece 65% de royalties aos artistas.', cta: 'Começar a Ouvir', secondaryCta: 'Saiba Mais', stats: { artists: 'Royalties de Artistas', royalties: 'Mais que Spotify', fans: 'Fãs Ativos', burned: '$THDR Queimados' } }, features: { title: 'Tudo que a Música Deveria Ser', subtitle: 'Um ecossistema completo para artistas, fãs e criadores', streaming: { title: 'Streaming Pago', description: 'Ganhe tokens $THDR por cada reprodução.' }, social: { title: 'Espaços Sociais', description: 'Feed, chats e espaços de áudio.' }, marketplace: { title: 'Mercado NFT', description: 'NFTs de música, ingressos e mercadorias.' }, ai: { title: 'Ferramentas IA', description: 'Gere música com IA.' }, governance: { title: 'Governança', description: 'Vote em decisões da plataforma.' }, wallet: { title: 'Carteira', description: 'Armazene $THDR e NFTs.' } }, tokenomics: { title: 'Tokenomics $THDR', subtitle: 'Distribuição justa. Deflacionário por design.', artistRoyalties: 'Royalties', fanRewards: 'Recompensas', platform: 'Plataforma', burning: '100% Taxas Queimadas' }, footer: { tagline: 'A Infraestrutura Musical Descentralizada Para O Futuro.', company: 'Empresa', resources: 'Recursos', legal: 'Legal', social: 'Social', copyright: '© 2026 Thundra Music Inc. Todos os direitos reservados.', quickLinks: 'Links Rápidos' }, common: { learnMore: 'Saiba Mais', comingSoon: 'Em Breve', joinWaitlist: 'Entrar na Lista', darkMode: 'Modo Escuro', lightMode: 'Modo Claro', language: 'Idioma' }, dashboard: { home: 'Início', search: 'Buscar', music: 'Música', library: 'Biblioteca', favorites: 'Favoritos', leaderboard: 'Ranking', profile: 'Perfil', wallet: 'Carteira', chat: 'Chat', learning: 'Aprendizado', market: 'Mercado', ai: 'IA', ads: 'Anúncios', artist: 'Estúdio', moderator: 'Moderador', admin: 'Admin', settings: 'Configurações', logout: 'Sair', upload: 'Enviar', earnings: 'Ganhos', followers: 'Seguidores', streams: 'Reproduções', likes: 'Curtidas' } },
  ar: { nav: { home: 'الرئيسية', discover: 'اكتشف', artists: 'للفنانين', marketplace: 'للأعمال', community: 'للمجتمع', business: 'للأعمال', login: 'تسجيل الدخول', signup: 'إنشاء حساب', getStarted: 'ابدأ' }, hero: { title: 'مستقبل', titleHighlight: 'الموسيقى لامركزي', subtitle: 'استمع واكسب وامتلك موسيقاك. Thundra Music تمنح الفنانين 65% من العائدات.', cta: 'ابدأ الاستماع', secondaryCta: 'اعرف المزيد', stats: { artists: 'عائدات الفنانين', royalties: 'أعلى من Spotify', fans: 'معجبون نشطون', burned: '$THDR محروق' } }, features: { title: 'كل ما يجب أن تكون عليه الموسيقى', subtitle: 'نظام بيئي كامل للفنانين والمعجبين والمبدعين', streaming: { title: 'بث مدفوع', description: 'اكسب رموز $THDR لكل استماع.' }, social: { title: 'مساحات اجتماعية', description: 'موجز ودردشات ومساحات صوتية.' }, marketplace: { title: 'سوق NFT', description: 'NFTs موسيقية وتذاكر وبضائع.' }, ai: { title: 'أدوات AI', description: 'أنشئ موسيقى بالذكاء الاصطناعي.' }, governance: { title: 'الحوكمة', description: 'صوّت على قرارات المنصة.' }, wallet: { title: 'المحفظة', description: 'خزّن $THDR و NFTs.' } }, tokenomics: { title: 'اقتصاديات $THDR', subtitle: 'توزيع عادل. انكماشي بالتصميم.', artistRoyalties: 'العائدات', fanRewards: 'مكافآت', platform: 'المنصة', burning: '100% رسوم محروقة' }, footer: { tagline: 'البنية التحتية للموسيقى اللامركزية للمستقبل.', company: 'الشركة', resources: 'الموارد', legal: 'قانوني', social: 'اجتماعي', copyright: '© 2026 Thundra Music Inc. جميع الحقوق محفوظة.', quickLinks: 'روابط سريعة' }, common: { learnMore: 'اعرف المزيد', comingSoon: 'قريباً', joinWaitlist: 'انضم للقائمة', darkMode: 'الوضع الداكن', lightMode: 'الوضع الفاتح', language: 'اللغة' }, dashboard: { home: 'الرئيسية', search: 'بحث', music: 'موسيقى', library: 'المكتبة', favorites: 'المفضلة', leaderboard: 'الترتيب', profile: 'الملف', wallet: 'المحفظة', chat: 'دردشة', learning: 'تعلم', market: 'السوق', ai: 'AI', ads: 'إعلانات', artist: 'استوديو', moderator: 'مشرف', admin: 'مدير', settings: 'إعدادات', logout: 'خروج', upload: 'رفع', earnings: 'أرباح', followers: 'متابعون', streams: 'استماعات', likes: 'إعجابات' } },
  rw: { nav: { home: 'Ahabanza', discover: 'Shakisha', artists: "Ku Bahanzi", marketplace: "Ku Bucuruzi", community: "Ku Muryango", business: "Ku Bucuruzi", login: 'Injira', signup: 'Iyandikishe', getStarted: 'Tangira' }, hero: { title: 'Ejo hazaza h\'', titleHighlight: 'Umuziki ni Decentralized', subtitle: 'Umva, wunguke, kandi utware umuziki wawe. Thundra Music itanga 65% ku bahanzi.', cta: 'Tangira Kumva', secondaryCta: 'Menya Byinshi', stats: { artists: 'Inyungu z\'Abahanzi', royalties: 'Birenze Spotify', fans: 'Abafana Bakora', burned: '$THDR Yashizwe' } }, features: { title: 'Ibyo Umuziki Ugomba Kuba', subtitle: 'Sisitemu yuzuye ku bahanzi, abafana, n\'abaremyi', streaming: { title: 'Kumva Wishyurwa', description: 'Bona $THDR kuri buri kumva.' }, social: { title: 'Ahahurira', description: 'Feed, ibiganiro, n\'audio spaces.' }, marketplace: { title: 'Isoko rya NFT', description: 'NFT z\'umuziki, amatike, n\'ibintu.' }, ai: { title: 'Ibikoresho bya AI', description: 'Kora umuziki na AI.' }, governance: { title: 'Ubuyobozi', description: 'Tora ku bisubizo.' }, wallet: { title: 'Agasanduku', description: 'Bika $THDR na NFT.' } }, tokenomics: { title: 'Tokenomics ya $THDR', subtitle: 'Kugabanya gukwiye.', artistRoyalties: 'Inyungu', fanRewards: 'Ibihembo', platform: 'Urubuga', burning: 'Amafaranga 100% Yashizwe' }, footer: { tagline: 'Ibikorwa by\'Umuziki Bitagenzuwe Ku Gihe Kizaza.', company: 'Sosiyete', resources: 'Ibikoresho', legal: 'Amategeko', social: 'Imiryango', copyright: '© 2026 Thundra Music Inc. Uburenganzira bwose burabikwa.', quickLinks: 'Amahuza Yihuse' }, common: { learnMore: 'Menya Byinshi', comingSoon: 'Biraza Vuba', joinWaitlist: 'Injira ku Rutonde', darkMode: 'Uburyo bwijimye', lightMode: 'Uburyo bwiza', language: 'Ururimi' }, dashboard: { home: 'Ahabanza', search: 'Shakisha', music: 'Umuziki', library: 'Isomero', favorites: 'Ibyakunzwe', leaderboard: 'Urutonde', profile: 'Umwirondoro', wallet: 'Agasanduku', chat: 'Ibiganiro', learning: 'Kwiga', market: 'Isoko', ai: 'AI', ads: 'Ibyamamaza', artist: 'Studio', moderator: 'Umunyamuryango', admin: 'Admin', settings: 'Igenamiterere', logout: 'Sohoka', upload: 'Shyiraho', earnings: 'Inyungu', followers: 'Abakurikira', streams: 'Kumva', likes: 'Gukunda' } },
  ln: { nav: { home: 'Ndako', discover: 'Luka', artists: "Mpo na Ba-Artistes", marketplace: "Mpo na Bizinesi", community: "Mpo na Communauté", business: "Mpo na Bizinesi", login: 'Kota', signup: 'Komisa Nkombo', getStarted: 'Banda' }, hero: { title: 'Lobi ya', titleHighlight: 'Musique ezali Décentralisé', subtitle: 'Yoka, zwa mbongo, mpe zala na musique na yo. Thundra Music epesaka ba-artistes 65%.', cta: 'Banda Koyoka', secondaryCta: 'Yeba Mingi', stats: { artists: 'Mbongo ya Ba-artistes', royalties: 'Koleka Spotify', fans: 'Bafans Bakasi', burned: '$THDR Etumbisami' } }, features: { title: 'Nyonso Musique Esengeli Kozala', subtitle: 'Système mobimba mpo na ba-artistes, bafans, mpe ba-créateurs', streaming: { title: 'Koyoka na Mbongo', description: 'Zwa $THDR mpo na koyoka nyonso.' }, social: { title: 'Bisika ya Social', description: 'Feed, masolo, mpe audio spaces.' }, marketplace: { title: 'Zando ya NFT', description: 'NFT ya musique, billets, mpe biloko.' }, ai: { title: 'Bisaleli ya AI', description: 'Sala musique na AI.' }, governance: { title: 'Governance', description: 'Vota na bikateli.' }, wallet: { title: 'Porte-monnaie', description: 'Bomba $THDR na NFT.' } }, tokenomics: { title: 'Tokenomics ya $THDR', subtitle: 'Kokabola malamu.', artistRoyalties: 'Mbongo', fanRewards: 'Makabo', platform: 'Plateforme', burning: 'Frais 100% Etumbisami' }, footer: { tagline: 'Infrastructure ya Musique Décentralisée Mpo na Lobi.', company: 'Société', resources: 'Bisaleli', legal: 'Mibeko', social: 'Social', copyright: '© 2026 Thundra Music Inc. Makoki nyonso ebombami.', quickLinks: 'Lien ya Mbangu' }, common: { learnMore: 'Yeba Mingi', comingSoon: 'Ezali Koya', joinWaitlist: 'Kota na Liste', darkMode: 'Mode ya Molili', lightMode: 'Mode ya Moi', language: 'Monoko' }, dashboard: { home: 'Ndako', search: 'Luka', music: 'Musique', library: 'Biblioteki', favorites: 'Balingami', leaderboard: 'Classement', profile: 'Profil', wallet: 'Porte-monnaie', chat: 'Masolo', learning: 'Koyekola', market: 'Zando', ai: 'AI', ads: 'Pub', artist: 'Studio', moderator: 'Modérateur', admin: 'Admin', settings: 'Paramètres', logout: 'Kobima', upload: 'Kotia', earnings: 'Mbongo', followers: 'Balandi', streams: 'Boyokeli', likes: 'Balingi' } },
  rn: { nav: { home: 'Ahabanza', discover: 'Rondera', artists: "Ku Bahanzi", marketplace: "Ku Bucuruzi", community: "Ku Muryango", business: "Ku Bucuruzi", login: 'Injira', signup: 'Iyandikishe', getStarted: 'Tangura' }, hero: { title: 'Ejo hazoza h\'', titleHighlight: 'Umuziki ni Decentralized', subtitle: 'Umva, wunguke, utware umuziki wawe. Thundra Music itanga 65% ku bahanzi.', cta: 'Tangura Kumva', secondaryCta: 'Menya Vyinshi', stats: { artists: 'Inyungu z\'Abahanzi', royalties: 'Birenze Spotify', fans: 'Abafana Bakora', burned: '$THDR Yashizwe' } }, features: { title: 'Ivyo Umuziki Ukwiye Kuba', subtitle: 'Sisitemu yuzuye ku bahanzi, abafana, n\'abaremyi', streaming: { title: 'Kumva Wishyurwa', description: 'Bona $THDR kuri buri kumva.' }, social: { title: 'Ahahurira', description: 'Feed, ibiganiro, n\'audio spaces.' }, marketplace: { title: 'Isoko rya NFT', description: 'NFT z\'umuziki, amatike, n\'ibintu.' }, ai: { title: 'Ibikoresho vya AI', description: 'Kora umuziki na AI.' }, governance: { title: 'Ubuyobozi', description: 'Tora ku bisubizo.' }, wallet: { title: 'Agasanduku', description: 'Bika $THDR na NFT.' } }, tokenomics: { title: 'Tokenomics ya $THDR', subtitle: 'Kugabanya bikwiye.', artistRoyalties: 'Inyungu', fanRewards: 'Ivyishimwe', platform: 'Urubuga', burning: 'Amafaranga 100% Yashizwe' }, footer: { tagline: 'Ibikorwa vy\'Umuziki Bitagenzuwe Ku Gihe Kizoza.', company: 'Sosiyete', resources: 'Ibikoresho', legal: 'Amategeko', social: 'Imiryango', copyright: '© 2026 Thundra Music Inc. Uburenganzira bwose burabikwa.', quickLinks: 'Amahuza Yihuta' }, common: { learnMore: 'Menya Vyinshi', comingSoon: 'Biraza Vuba', joinWaitlist: 'Injira ku Rutonde', darkMode: 'Uburyo bwijimye', lightMode: 'Uburyo bwiza', language: 'Ururimi' }, dashboard: { home: 'Ahabanza', search: 'Rondera', music: 'Umuziki', library: 'Isomero', favorites: 'Ibikunzwe', leaderboard: 'Urutonde', profile: 'Umwirondoro', wallet: 'Agasanduku', chat: 'Ibiganiro', learning: 'Kwiga', market: 'Isoko', ai: 'AI', ads: 'Ibyamamaza', artist: 'Studio', moderator: 'Umunyamuryango', admin: 'Admin', settings: 'Igenamiterere', logout: 'Sohoka', upload: 'Shira', earnings: 'Inyungu', followers: 'Abakurikira', streams: 'Kumva', likes: 'Gukunda' } },
  yo: { nav: { home: 'Ilé', discover: 'Ṣàwárí', artists: "Fún Àwọn Oṣere", marketplace: "Fún Iṣowo", community: "Fún Àwùjọ", business: "Fún Iṣowo", login: 'Wọlé', signup: 'Forúkọsílẹ̀', getStarted: 'Bẹ̀rẹ̀' }, hero: { title: 'Ọjọ́ iwájú ti', titleHighlight: 'Orin jẹ́ Alailowoti', subtitle: 'Gbọ́, jèrè, kí o sì ní orin rẹ. Thundra Music fún àwọn oṣere ní 65% ti owó.', cta: 'Bẹ̀rẹ̀ Gbígbọ́', secondaryCta: 'Kọ́ Sí i', stats: { artists: 'Owó Àwọn Oṣere', royalties: 'Ju Spotify lọ', fans: 'Àwọn Olùfẹ́', burned: '$THDR Ti jó' } }, features: { title: 'Gbogbo Ohun Tí Orin Yẹ Kí O Jẹ́', subtitle: 'Ètò pípé fún àwọn oṣere, olùfẹ́, àti aṣẹ̀dá', streaming: { title: 'Gbígbọ́ Pẹ̀lú Owó', description: 'Gba $THDR fún gbígbọ́ kọ̀ọ̀kan.' }, social: { title: 'Àwọn Àyè Àwùjọ', description: 'Feed, ìjíròrò, àti audio spaces.' }, marketplace: { title: 'Ọjà NFT', description: 'NFT orin, tíkẹ́ẹ̀tì, àti ọjà.' }, ai: { title: 'Àwọn Irinṣẹ́ AI', description: 'Ṣẹ̀dá orin pẹ̀lú AI.' }, governance: { title: 'Ìṣàkóso', description: 'Dìbò lórí àwọn ìpinnu.' }, wallet: { title: 'Àpamọ́wọ́', description: 'Fi $THDR àti NFT pamọ́.' } }, tokenomics: { title: 'Tokenomics $THDR', subtitle: 'Pínpín ododo.', artistRoyalties: 'Owó', fanRewards: 'Ẹ̀bùn', platform: 'Pẹpẹ', burning: 'Owó 100% Ti jó' }, footer: { tagline: 'Àmúyẹ́ Orin Alailowoti Fún Ọjọ́ Iwájú.', company: 'Ilé-iṣẹ́', resources: 'Àwọn Ohun Èlò', legal: 'Òfin', social: 'Àwùjọ', copyright: '© 2026 Thundra Music Inc. Gbogbo ẹ̀tọ́ ni a pa mọ́.', quickLinks: 'Àwọn Ìsopọ̀ Kíákíá' }, common: { learnMore: 'Kọ́ Sí i', comingSoon: 'Ó ń bọ̀', joinWaitlist: 'Darapọ̀ mọ́ Àtòjọ', darkMode: 'Ètò Òkùnkùn', lightMode: 'Ètò Ìmọ́lẹ̀', language: 'Èdè' }, dashboard: { home: 'Ilé', search: 'Ṣàwárí', music: 'Orin', library: 'Ilé-ìkàwé', favorites: 'Àwọn Ayanfẹ́', leaderboard: 'Àtòjọ', profile: 'Profaili', wallet: 'Àpamọ́wọ́', chat: 'Ìjíròrò', learning: 'Ẹ̀kọ́', market: 'Ọjà', ai: 'AI', ads: 'Ìpolówó', artist: 'Studio', moderator: 'Olùdarí', admin: 'Admin', settings: 'Ètò', logout: 'Jáde', upload: 'Gbe sókè', earnings: 'Owó', followers: 'Àwọn Olùtẹ̀lé', streams: 'Gbígbọ́', likes: 'Fẹ́ràn' } },
  zu: { nav: { home: 'Ekhaya', discover: 'Thola', artists: "Kwabacula", marketplace: "Kwezamabhizinisi", community: "Komphakathi", business: "Kwezamabhizinisi", login: 'Ngena', signup: 'Bhalisa', getStarted: 'Qala' }, hero: { title: 'Ikusasa le', titleHighlight: 'Mculo yi-Decentralized', subtitle: 'Lalela, zuza, uphinde ube nomculo wakho. Thundra Music inika abaculo 65%.', cta: 'Qala Ukulalela', secondaryCta: 'Funda Kabanzi', stats: { artists: 'Imali Yabacula', royalties: 'Ngaphezu kwe-Spotify', fans: 'Abalandeli Abasebenzayo', burned: '$THDR Eshisiwe' } }, features: { title: 'Konke Umculo Okufanele Ube Yikho', subtitle: 'Uhlelo oluphelele lwabacula, abalandeli, nabadali', streaming: { title: 'Ukulalela Ngemali', description: 'Thola $THDR ngokulalela ngakunye.' }, social: { title: 'Izindawo Zomphakathi', description: 'Feed, izingxoxo, nama-audio spaces.' }, marketplace: { title: 'Imakethe ye-NFT', description: 'NFT zomculo, amathikithi, nezimpahla.' }, ai: { title: 'Amathuluzi e-AI', description: 'Dala umculo nge-AI.' }, governance: { title: 'Ukubusa', description: 'Vota ezinqumeni.' }, wallet: { title: 'Isikhwama', description: 'Gcina $THDR ne-NFT.' } }, tokenomics: { title: 'I-Tokenomics ye-$THDR', subtitle: 'Ukwabiwa okufanele.', artistRoyalties: 'Imali', fanRewards: 'Imivuzo', platform: 'Inkundla', burning: 'Izindleko Ezingu-100% Zishisiwe' }, footer: { tagline: 'Ingqalasizinda Yomculo E-Decentralized Yekusasa.', company: 'Inkampani', resources: 'Izinsiza', legal: 'Ezomthetho', social: 'Ezenhlalo', copyright: '© 2026 Thundra Music Inc. Onke amalungelo agodliwe.', quickLinks: 'Izixhumanisi Ezisheshayo' }, common: { learnMore: 'Funda Kabanzi', comingSoon: 'Kuyeza', joinWaitlist: 'Joyina Uhlu', darkMode: 'Imodi Emnyama', lightMode: 'Imodi Ekhanyayo', language: 'Ulimi' }, dashboard: { home: 'Ekhaya', search: 'Sesha', music: 'Umculo', library: 'Umtapo', favorites: 'Izintandokazi', leaderboard: 'Uhlu', profile: 'Iphrofayela', wallet: 'Isikhwama', chat: 'Ingxoxo', learning: 'Ukufunda', market: 'Imakethe', ai: 'AI', ads: 'Izikhangiso', artist: 'I-Studio', moderator: 'Umphathi', admin: 'U-Admin', settings: 'Izilungiselelo', logout: 'Phuma', upload: 'Layisha', earnings: 'Inzuzo', followers: 'Abalandeli', streams: 'Ukulalela', likes: 'Thanda' } },
  wo: { nav: { home: 'Kër', discover: 'Seet', artists: "Ngir Artistes yi", marketplace: "Ngir Bisness", community: "Ngir Communauté", business: "Ngir Bisness", login: 'Dugg', signup: 'Bindu', getStarted: 'Tambali' }, hero: { title: 'Élék bi', titleHighlight: 'Musique moy Décentralisé', subtitle: 'Déglu, wàcc, te am musique sa. Thundra Music day jox artistes yi 65%.', cta: 'Tambali Déglu', secondaryCta: 'Xam lu ëpp', stats: { artists: 'Xaalis Artistes yi', royalties: 'Gën Spotify', fans: 'Fans yu Nek', burned: '$THDR yu Dàqq' } }, features: { title: 'Lépp lu Musique Waroon a Doon', subtitle: 'Système bu mat ngir artistes, fans, ak créateurs', streaming: { title: 'Déglu ak Xaalis', description: 'Am $THDR bu njëkk.' }, social: { title: 'Bérab Social', description: 'Feed, waxtaan, ak audio spaces.' }, marketplace: { title: 'Marse NFT', description: 'NFT Musique, biye, ak yeneen.' }, ai: { title: 'Jumtukaay AI', description: 'Def musique ak AI.' }, governance: { title: 'Governance', description: 'Tann ci décisions yi.' }, wallet: { title: 'Porte-monnaie', description: 'Denc $THDR ak NFT.' } }, tokenomics: { title: 'Tokenomics $THDR', subtitle: 'Séddaaral bu baax.', artistRoyalties: 'Xaalis', fanRewards: 'Njeximu', platform: 'Plateforme', burning: 'Frais yu 100% Dàqq' }, footer: { tagline: 'Infrastructure Musique bu Décentralisé Ngir Élék.', company: 'Société', resources: 'Jumtukaay', legal: 'Loi', social: 'Social', copyright: '© 2026 Thundra Music Inc. Mbir yépp ñu ngi ko denc.', quickLinks: 'Liens yu Gaaw' }, common: { learnMore: 'Xam lu ëpp', comingSoon: 'Dina Ñëw', joinWaitlist: 'Dugg ci Liist', darkMode: 'Mode Lëndëm', lightMode: 'Mode Leer', language: 'Làkk' }, dashboard: { home: 'Kër', search: 'Seet', music: 'Musique', library: 'Bibliothèque', favorites: 'Yu Bëgg', leaderboard: 'Liist', profile: 'Profil', wallet: 'Porte-monnaie', chat: 'Waxtaan', learning: 'Jàng', market: 'Marse', ai: 'AI', ads: 'Pub', artist: 'Studio', moderator: 'Modérateur', admin: 'Admin', settings: 'Paramètres', logout: 'Génn', upload: 'Yóbbu', earnings: 'Xaalis', followers: 'Toppkat', streams: 'Déglu', likes: 'Bëgg' } },
  ro: { nav: { home: 'Acasă', discover: 'Descoperă', artists: 'Pentru Artiști', marketplace: 'Pentru Afaceri', community: 'Pentru Comunitate', business: 'Pentru Afaceri', login: 'Autentificare', signup: 'Înregistrare', getStarted: 'Începe' }, hero: { title: 'Viitorul', titleHighlight: 'Muzicii este Descentralizat', subtitle: 'Ascultă, câștigă și deține muzica ta. Thundra Music oferă artiștilor 65% din drepturi.', cta: 'Începe să Asculți', secondaryCta: 'Află Mai Multe', stats: { artists: 'Drepturi Artiști', royalties: 'Mai mult decât Spotify', fans: 'Fani Activi', burned: '$THDR Ars' } }, features: { title: 'Tot Ce Ar Trebui Să Fie Muzica', subtitle: 'Un ecosistem complet pentru artiști, fani și creatori', streaming: { title: 'Streaming Plătit', description: 'Câștigă $THDR pentru fiecare stream.' }, social: { title: 'Spații Sociale', description: 'Feed, chat și spații audio.' }, marketplace: { title: 'Piață NFT', description: 'NFT-uri muzicale, bilete și merchandise.' }, ai: { title: 'Instrumente AI', description: 'Creează muzică cu AI.' }, governance: { title: 'Guvernanță', description: 'Votează pentru decizii.' }, wallet: { title: 'Portofel', description: 'Stochează $THDR și NFT-uri.' } }, tokenomics: { title: 'Tokenomics $THDR', subtitle: 'Distribuție echitabilă. Deflaționar prin design.', artistRoyalties: 'Drepturi', fanRewards: 'Recompense', platform: 'Platformă', burning: '100% Taxe Arse' }, footer: { tagline: 'Infrastructura Muzicală Descentralizată Pentru Viitor.', company: 'Companie', resources: 'Resurse', legal: 'Legal', social: 'Social', copyright: '© 2026 Thundra Music Inc. Toate drepturile rezervate.', quickLinks: 'Linkuri Rapide' }, common: { learnMore: 'Află Mai Multe', comingSoon: 'În Curând', joinWaitlist: 'Înscrie-te', darkMode: 'Mod Întunecat', lightMode: 'Mod Luminos', language: 'Limbă' }, dashboard: { home: 'Acasă', search: 'Caută', music: 'Muzică', library: 'Bibliotecă', favorites: 'Favorite', leaderboard: 'Clasament', profile: 'Profil', wallet: 'Portofel', chat: 'Chat', learning: 'Învățare', market: 'Piață', ai: 'AI', ads: 'Reclame', artist: 'Studio', moderator: 'Moderator', admin: 'Admin', settings: 'Setări', logout: 'Deconectare', upload: 'Încarcă', earnings: 'Câștiguri', followers: 'Urmăritori', streams: 'Streams', likes: 'Aprecieri' } },
  ru: { nav: { home: 'Главная', discover: 'Открыть', artists: 'Для Артистов', marketplace: 'Для Бизнеса', community: 'Для Сообщества', business: 'Для Бизнеса', login: 'Войти', signup: 'Регистрация', getStarted: 'Начать' }, hero: { title: 'Будущее', titleHighlight: 'Музыки Децентрализовано', subtitle: 'Слушайте, зарабатывайте и владейте своей музыкой. Thundra Music даёт артистам 65% роялти.', cta: 'Начать Слушать', secondaryCta: 'Узнать Больше', stats: { artists: 'Роялти Артистов', royalties: 'Больше чем Spotify', fans: 'Активные Фанаты', burned: '$THDR Сожжено' } }, features: { title: 'Всё, Чем Должна Быть Музыка', subtitle: 'Полная экосистема для артистов, фанатов и создателей', streaming: { title: 'Платный Стриминг', description: 'Получайте $THDR за каждый стрим.' }, social: { title: 'Социальные Пространства', description: 'Лента, чаты и аудио пространства.' }, marketplace: { title: 'NFT Маркетплейс', description: 'Музыкальные NFT, билеты и мерч.' }, ai: { title: 'AI Инструменты', description: 'Создавайте музыку с AI.' }, governance: { title: 'Управление', description: 'Голосуйте за решения.' }, wallet: { title: 'Кошелёк', description: 'Храните $THDR и NFT.' } }, tokenomics: { title: 'Токеномика $THDR', subtitle: 'Справедливое распределение. Дефляционный дизайн.', artistRoyalties: 'Роялти', fanRewards: 'Награды', platform: 'Платформа', burning: '100% Комиссий Сжигается' }, footer: { tagline: 'Децентрализованная Музыкальная Инфраструктура Для Будущего.', company: 'Компания', resources: 'Ресурсы', legal: 'Правовая информация', social: 'Социальные сети', copyright: '© 2026 Thundra Music Inc. Все права защищены.', quickLinks: 'Быстрые Ссылки' }, common: { learnMore: 'Узнать Больше', comingSoon: 'Скоро', joinWaitlist: 'Присоединиться', darkMode: 'Тёмный Режим', lightMode: 'Светлый Режим', language: 'Язык' }, dashboard: { home: 'Главная', search: 'Поиск', music: 'Музыка', library: 'Библиотека', favorites: 'Избранное', leaderboard: 'Рейтинг', profile: 'Профиль', wallet: 'Кошелёк', chat: 'Чат', learning: 'Обучение', market: 'Маркет', ai: 'AI', ads: 'Реклама', artist: 'Студия', moderator: 'Модератор', admin: 'Админ', settings: 'Настройки', logout: 'Выход', upload: 'Загрузить', earnings: 'Заработок', followers: 'Подписчики', streams: 'Стримы', likes: 'Лайки' } },
  lg: { nav: { home: 'Awaaka', discover: 'Noonya', artists: "Eri Abakulembeze b'Ennyimba", marketplace: "Eri Bizinensi", community: "Eri Ekitundu", business: "Eri Bizinensi", login: 'Yingira', signup: 'Wewandiise', getStarted: 'Tandika' }, hero: { title: 'Ebiseera Eby\'omu', titleHighlight: 'Ennyimba Biri Decentralized', subtitle: 'Wulira, fumba, era oteeke ennyimba yo. Thundra Music ewaayo 65% eri abakulembeze.', cta: 'Tandika Okuwulira', secondaryCta: 'Manya Ebisingawo', stats: { artists: 'Ensimbi z\'Abakulembeze', royalties: 'Okusinga Spotify', fans: 'Abafaana Abakozi', burned: '$THDR Eyokeddwa' } }, features: { title: 'Bonna Ennyimba By\'etekeddwa Okuba', subtitle: 'Enkola ennungi eri abakulembeze, abafaana, n\'abakozi', streaming: { title: 'Okuwulira n\'Ensimbi', description: 'Funa $THDR buli lwe owulira.' }, social: { title: 'Ebifo bya Social', description: 'Feed, okwogera, n\'audio spaces.' }, marketplace: { title: 'Katale ka NFT', description: 'NFT z\'ennyimba, tiketi, n\'ebintu.' }, ai: { title: 'Ebikozesebwa bya AI', description: 'Kola ennyimba ne AI.' }, governance: { title: 'Obufuzi', description: 'Voota ku biragiro.' }, wallet: { title: 'Akadaala', description: 'Tereka $THDR ne NFT.' } }, tokenomics: { title: 'Tokenomics ya $THDR', subtitle: 'Okugaba obulungi.', artistRoyalties: 'Ensimbi', fanRewards: 'Ebirabo', platform: 'Pulatifomu', burning: 'Okwokya 100%' }, footer: { tagline: "Ebyetaagisa By'ennyimba Ebiri Decentralized Eri Obulamu Obujja.", company: 'Kkampuni', resources: 'Ebyetaagisa', legal: 'Amateeka', social: 'Social', copyright: '© 2026 Thundra Music Inc. Obuyinza bwonna butereddwa.', quickLinks: 'Amalinki Amangu' }, common: { learnMore: 'Manya Ebisingawo', comingSoon: 'Bijja', joinWaitlist: 'Yingira mu Lukalala', darkMode: 'Ensawo Enzirakitiza', lightMode: 'Ensawo Eyaka', language: 'Olulimi' }, dashboard: { home: 'Awaaka', search: 'Noonya', music: 'Ennyimba', library: 'Esomero', favorites: 'Ebisinga', leaderboard: 'Lukalala', profile: 'Profayiro', wallet: 'Akadaala', chat: 'Okwogera', learning: 'Okuyiga', market: 'Katale', ai: 'AI', ads: 'Byokuzaala', artist: 'Studio', moderator: 'Omutundutundu', admin: 'Admin', settings: 'Enteekateeka', logout: 'Fuluma', upload: 'Teeka', earnings: 'Ensimbi', followers: 'Abagoberera', streams: 'Okuwulira', likes: 'Okwagala' } },
  uk: { nav: { home: 'Головна', discover: 'Відкрити', artists: 'Для Артистів', marketplace: 'Для Бізнесу', community: 'Для Спільноти', business: 'Для Бізнесу', login: 'Увійти', signup: 'Реєстрація', getStarted: 'Почати' }, hero: { title: 'Майбутнє', titleHighlight: 'Музики Децентралізоване', subtitle: 'Слухайте, заробляйте та володійте своєю музикою. Thundra Music дає артистам 65% роялті.', cta: 'Почати Слухати', secondaryCta: 'Дізнатися Більше', stats: { artists: 'Роялті Артистів', royalties: 'Більше ніж Spotify', fans: 'Активні Фанати', burned: '$THDR Спалено' } }, features: { title: 'Усе, Чим Має Бути Музика', subtitle: 'Повна екосистема для артистів, фанатів та творців', streaming: { title: 'Платний Стрімінг', description: 'Отримуйте $THDR за кожен стрім.' }, social: { title: 'Соціальні Простори', description: 'Стрічка, чати та аудіо простори.' }, marketplace: { title: 'NFT Маркетплейс', description: 'Музичні NFT, квитки та мерч.' }, ai: { title: 'AI Інструменти', description: 'Створюйте музику з AI.' }, governance: { title: 'Управління', description: 'Голосуйте за рішення.' }, wallet: { title: 'Гаманець', description: 'Зберігайте $THDR та NFT.' } }, tokenomics: { title: 'Токеноміка $THDR', subtitle: 'Справедливий розподіл. Дефляційний дизайн.', artistRoyalties: 'Роялті', fanRewards: 'Нагороди', platform: 'Платформа', burning: '100% Комісій Спалюється' }, footer: { tagline: 'Децентралізована Музична Інфраструктура Для Майбутнього.', company: 'Компанія', resources: 'Ресурси', legal: 'Правова інформація', social: 'Соціальні мережі', copyright: '© 2026 Thundra Music Inc. Усі права захищені.', quickLinks: 'Швидкі Посилання' }, common: { learnMore: 'Дізнатися Більше', comingSoon: 'Незабаром', joinWaitlist: 'Приєднатися', darkMode: 'Темний Режим', lightMode: 'Світлий Режим', language: 'Мова' }, dashboard: { home: 'Головна', search: 'Пошук', music: 'Музика', library: 'Бібліотека', favorites: 'Обране', leaderboard: 'Рейтинг', profile: 'Профіль', wallet: 'Гаманець', chat: 'Чат', learning: 'Навчання', market: 'Маркет', ai: 'AI', ads: 'Реклама', artist: 'Студія', moderator: 'Модератор', admin: 'Адмін', settings: 'Налаштування', logout: 'Вихід', upload: 'Завантажити', earnings: 'Заробіток', followers: 'Підписники', streams: 'Стріми', likes: 'Лайки' } },
  tl: { nav: { home: 'Bahay', discover: 'Tuklasin', artists: 'Para sa mga Artista', marketplace: 'Para sa Negosyo', community: 'Para sa Komunidad', business: 'Para sa Negosyo', login: 'Mag-login', signup: 'Mag-signup', getStarted: 'Magsimula' }, hero: { title: 'Ang Kinabukasan ng', titleHighlight: 'Musika ay Desentralisado', subtitle: 'Makinig, kumita, at mag-ari ng iyong musika. Nagbibigay ang Thundra Music ng 65% royalties sa mga artista.', cta: 'Magsimulang Makinig', secondaryCta: 'Matuto Pa', stats: { artists: 'Royalties ng Artista', royalties: 'Higit sa Spotify', fans: 'Aktibong Fans', burned: '$THDR na Sinunog' } }, features: { title: 'Lahat ng Dapat na Musika', subtitle: 'Isang kumpletong ecosystem para sa mga artista, fans, at creators', streaming: { title: 'Bayad na Streaming', description: 'Kumita ng $THDR sa bawat stream.' }, social: { title: 'Social Spaces', description: 'Feed, chats, at audio spaces.' }, marketplace: { title: 'NFT Marketplace', description: 'Music NFTs, tickets, at merchandise.' }, ai: { title: 'AI Tools', description: 'Gumawa ng musika gamit ang AI.' }, governance: { title: 'Governance', description: 'Bumoto sa mga desisyon.' }, wallet: { title: 'Wallet', description: 'Itago ang $THDR at NFT.' } }, tokenomics: { title: '$THDR Tokenomics', subtitle: 'Patas na distribusyon.', artistRoyalties: 'Royalties', fanRewards: 'Mga Gantimpala', platform: 'Platform', burning: '100% Fees Sinunog' }, footer: { tagline: 'Ang Desentralisadong Imprastraktura ng Musika Para sa Kinabukasan.', company: 'Kumpanya', resources: 'Mga Resources', legal: 'Legal', social: 'Social', copyright: '© 2026 Thundra Music Inc. Lahat ng karapatan ay nakalaan.', quickLinks: 'Mabilis na Links' }, common: { learnMore: 'Matuto Pa', comingSoon: 'Paparating Na', joinWaitlist: 'Sumali sa Waitlist', darkMode: 'Dark Mode', lightMode: 'Light Mode', language: 'Wika' }, dashboard: { home: 'Bahay', search: 'Maghanap', music: 'Musika', library: 'Library', favorites: 'Mga Paborito', leaderboard: 'Leaderboard', profile: 'Profile', wallet: 'Wallet', chat: 'Chat', learning: 'Pag-aaral', market: 'Market', ai: 'AI', ads: 'Ads', artist: 'Studio', moderator: 'Moderator', admin: 'Admin', settings: 'Settings', logout: 'Logout', upload: 'Upload', earnings: 'Kita', followers: 'Followers', streams: 'Streams', likes: 'Likes' } },
  vi: { nav: { home: 'Trang Chủ', discover: 'Khám Phá', artists: 'Dành Cho Nghệ Sĩ', marketplace: 'Dành Cho Doanh Nghiệp', community: 'Dành Cho Cộng Đồng', business: 'Dành Cho Doanh Nghiệp', login: 'Đăng Nhập', signup: 'Đăng Ký', getStarted: 'Bắt Đầu' }, hero: { title: 'Tương Lai Của', titleHighlight: 'Âm Nhạc Là Phi Tập Trung', subtitle: 'Nghe, kiếm tiền và sở hữu âm nhạc của bạn. Thundra Music trao cho nghệ sĩ 65% tiền bản quyền.', cta: 'Bắt Đầu Nghe', secondaryCta: 'Tìm Hiểu Thêm', stats: { artists: 'Tiền Bản Quyền Nghệ Sĩ', royalties: 'Cao Hơn Spotify', fans: 'Fan Tích Cực', burned: '$THDR Đã Đốt' } }, features: { title: 'Tất Cả Những Gì Âm Nhạc Nên Là', subtitle: 'Một hệ sinh thái hoàn chỉnh cho nghệ sĩ, fan và người sáng tạo', streaming: { title: 'Streaming Trả Phí', description: 'Kiếm $THDR cho mỗi lượt nghe.' }, social: { title: 'Không Gian Xã Hội', description: 'Feed, chat và audio spaces.' }, marketplace: { title: 'Chợ NFT', description: 'NFT âm nhạc, vé và hàng hóa.' }, ai: { title: 'Công Cụ AI', description: 'Tạo nhạc với AI.' }, governance: { title: 'Quản Trị', description: 'Bỏ phiếu cho các quyết định.' }, wallet: { title: 'Ví', description: 'Lưu trữ $THDR và NFT.' } }, tokenomics: { title: 'Tokenomics $THDR', subtitle: 'Phân phối công bằng. Thiết kế giảm phát.', artistRoyalties: 'Bản Quyền', fanRewards: 'Phần Thưởng', platform: 'Nền Tảng', burning: '100% Phí Đốt' }, footer: { tagline: 'Cơ Sở Hạ Tầng Âm Nhạc Phi Tập Trung Cho Tương Lai.', company: 'Công Ty', resources: 'Tài Nguyên', legal: 'Pháp Lý', social: 'Mạng Xã Hội', copyright: '© 2026 Thundra Music Inc. Bảo lưu mọi quyền.', quickLinks: 'Liên Kết Nhanh' }, common: { learnMore: 'Tìm Hiểu Thêm', comingSoon: 'Sắp Ra Mắt', joinWaitlist: 'Tham Gia Danh Sách', darkMode: 'Chế Độ Tối', lightMode: 'Chế Độ Sáng', language: 'Ngôn Ngữ' }, dashboard: { home: 'Trang Chủ', search: 'Tìm Kiếm', music: 'Âm Nhạc', library: 'Thư Viện', favorites: 'Yêu Thích', leaderboard: 'Bảng Xếp Hạng', profile: 'Hồ Sơ', wallet: 'Ví', chat: 'Chat', learning: 'Học Tập', market: 'Chợ', ai: 'AI', ads: 'Quảng Cáo', artist: 'Studio', moderator: 'Moderator', admin: 'Admin', settings: 'Cài Đặt', logout: 'Đăng Xuất', upload: 'Tải Lên', earnings: 'Thu Nhập', followers: 'Người Theo Dõi', streams: 'Lượt Nghe', likes: 'Thích' } },
  hi: { nav: { home: 'होम', discover: 'खोजें', artists: 'कलाकारों के लिए', marketplace: 'व्यवसाय के लिए', community: 'समुदाय के लिए', business: 'व्यवसाय के लिए', login: 'लॉगिन', signup: 'साइन अप', getStarted: 'शुरू करें' }, hero: { title: 'संगीत का भविष्य', titleHighlight: 'विकेंद्रीकृत है', subtitle: 'सुनें, कमाएं और अपने संगीत के मालिक बनें। Thundra Music कलाकारों को 65% रॉयल्टी देता है।', cta: 'सुनना शुरू करें', secondaryCta: 'और जानें', stats: { artists: 'कलाकार रॉयल्टी', royalties: 'Spotify से अधिक', fans: 'सक्रिय प्रशंसक', burned: '$THDR जला दिया' } }, features: { title: 'संगीत जो होना चाहिए', subtitle: 'कलाकारों, प्रशंसकों और निर्माताओं के लिए एक पूर्ण पारिस्थितिकी तंत्र', streaming: { title: 'भुगतान स्ट्रीमिंग', description: 'हर स्ट्रीम के लिए $THDR कमाएं।' }, social: { title: 'सामाजिक स्थान', description: 'फीड, चैट और ऑडियो स्पेस।' }, marketplace: { title: 'NFT बाज़ार', description: 'संगीत NFT, टिकट और सामान।' }, ai: { title: 'AI उपकरण', description: 'AI से संगीत बनाएं।' }, governance: { title: 'शासन', description: 'निर्णयों पर मतदान करें।' }, wallet: { title: 'वॉलेट', description: '$THDR और NFT स्टोर करें।' } }, tokenomics: { title: '$THDR टोकनोमिक्स', subtitle: 'उचित वितरण।', artistRoyalties: 'रॉयल्टी', fanRewards: 'पुरस्कार', platform: 'प्लेटफॉर्म', burning: '100% शुल्क जला दिया' }, footer: { tagline: 'भविष्य के लिए विकेंद्रीकृत संगीत बुनियादी ढांचा।', company: 'कंपनी', resources: 'संसाधन', legal: 'कानूनी', social: 'सामाजिक', copyright: '© 2026 Thundra Music Inc. सर्वाधिकार सुरक्षित।', quickLinks: 'त्वरित लिंक' }, common: { learnMore: 'और जानें', comingSoon: 'जल्द आ रहा है', joinWaitlist: 'सूची में शामिल हों', darkMode: 'डार्क मोड', lightMode: 'लाइट मोड', language: 'भाषा' }, dashboard: { home: 'होम', search: 'खोजें', music: 'संगीत', library: 'लाइब्रेरी', favorites: 'पसंदीदा', leaderboard: 'लीडरबोर्ड', profile: 'प्रोफाइल', wallet: 'वॉलेट', chat: 'चैट', learning: 'सीखना', market: 'बाज़ार', ai: 'AI', ads: 'विज्ञापन', artist: 'स्टूडियो', moderator: 'मॉडरेटर', admin: 'एडमिन', settings: 'सेटिंग्स', logout: 'लॉगआउट', upload: 'अपलोड', earnings: 'कमाई', followers: 'फॉलोअर्स', streams: 'स्ट्रीम्स', likes: 'लाइक्स' } },
  tr: { nav: { home: 'Ana Sayfa', discover: 'Keşfet', artists: 'Sanatçılar İçin', marketplace: 'İşletmeler İçin', community: 'Topluluk İçin', business: 'İşletmeler İçin', login: 'Giriş', signup: 'Kayıt', getStarted: 'Başla' }, hero: { title: 'Müziğin Geleceği', titleHighlight: 'Merkezi Değil', subtitle: 'Dinle, kazan ve müziğine sahip ol. Thundra Music sanatçılara %65 telif hakkı veriyor.', cta: 'Dinlemeye Başla', secondaryCta: 'Daha Fazla Bilgi', stats: { artists: 'Sanatçı Telif Hakları', royalties: "Spotify'dan Yüksek", fans: 'Aktif Hayranlar', burned: '$THDR Yakıldı' } }, features: { title: 'Müziğin Olması Gereken Her Şey', subtitle: 'Sanatçılar, hayranlar ve içerik oluşturucular için eksiksiz ekosistem', streaming: { title: 'Ücretli Dinleme', description: 'Her dinleme için $THDR kazan.' }, social: { title: 'Sosyal Alanlar', description: 'Akış, sohbet ve ses alanları.' }, marketplace: { title: 'NFT Pazarı', description: 'Müzik NFT\'leri, biletler ve ürünler.' }, ai: { title: 'AI Araçları', description: 'AI ile müzik oluştur.' }, governance: { title: 'Yönetişim', description: 'Kararlara oy ver.' }, wallet: { title: 'Cüzdan', description: '$THDR ve NFT sakla.' } }, tokenomics: { title: '$THDR Tokenomics', subtitle: 'Adil dağıtım. Deflasyonist tasarım.', artistRoyalties: 'Telif Hakları', fanRewards: 'Ödüller', platform: 'Platform', burning: '%100 Ücretler Yakıldı' }, footer: { tagline: 'Gelecek İçin Merkezi Olmayan Müzik Altyapısı.', company: 'Şirket', resources: 'Kaynaklar', legal: 'Yasal', social: 'Sosyal', copyright: '© 2026 Thundra Music Inc. Tüm hakları saklıdır.', quickLinks: 'Hızlı Bağlantılar' }, common: { learnMore: 'Daha Fazla', comingSoon: 'Yakında', joinWaitlist: 'Listeye Katıl', darkMode: 'Karanlık Mod', lightMode: 'Aydınlık Mod', language: 'Dil' }, dashboard: { home: 'Ana Sayfa', search: 'Ara', music: 'Müzik', library: 'Kütüphane', favorites: 'Favoriler', leaderboard: 'Sıralama', profile: 'Profil', wallet: 'Cüzdan', chat: 'Sohbet', learning: 'Öğrenme', market: 'Pazar', ai: 'AI', ads: 'Reklamlar', artist: 'Stüdyo', moderator: 'Moderatör', admin: 'Admin', settings: 'Ayarlar', logout: 'Çıkış', upload: 'Yükle', earnings: 'Kazançlar', followers: 'Takipçiler', streams: 'Dinlemeler', likes: 'Beğeniler' } },
  hr: { nav: { home: 'Početna', discover: 'Otkrij', artists: 'Za Umjetnike', marketplace: 'Za Tvrtke', community: 'Za Zajednicu', business: 'Za Tvrtke', login: 'Prijava', signup: 'Registracija', getStarted: 'Započni' }, hero: { title: 'Budućnost', titleHighlight: 'Glazbe je Decentralizirana', subtitle: 'Slušaj, zarađuj i posjeduj svoju glazbu. Thundra Music daje umjetnicima 65% tantijema.', cta: 'Počni Slušati', secondaryCta: 'Saznaj Više', stats: { artists: 'Tantijeme Umjetnika', royalties: 'Više od Spotifyja', fans: 'Aktivni Fanovi', burned: '$THDR Spaljeno' } }, features: { title: 'Sve Što Glazba Treba Biti', subtitle: 'Kompletan ekosustav za umjetnike, fanove i kreatore', streaming: { title: 'Plaćeno Slušanje', description: 'Zaradi $THDR za svako slušanje.' }, social: { title: 'Društveni Prostori', description: 'Feed, chatovi i audio prostori.' }, marketplace: { title: 'NFT Tržište', description: 'Glazbeni NFT-ovi, ulaznice i roba.' }, ai: { title: 'AI Alati', description: 'Stvaraj glazbu s AI.' }, governance: { title: 'Upravljanje', description: 'Glasaj za odluke.' }, wallet: { title: 'Novčanik', description: 'Pohrani $THDR i NFT.' } }, tokenomics: { title: '$THDR Tokenomics', subtitle: 'Pravedna distribucija.', artistRoyalties: 'Tantijeme', fanRewards: 'Nagrade', platform: 'Platforma', burning: '100% Naknada Spaljeno' }, footer: { tagline: 'Decentralizirana Glazbena Infrastruktura Za Budućnost.', company: 'Tvrtka', resources: 'Resursi', legal: 'Pravno', social: 'Društveno', copyright: '© 2026 Thundra Music Inc. Sva prava pridržana.', quickLinks: 'Brze Veze' }, common: { learnMore: 'Saznaj Više', comingSoon: 'Uskoro', joinWaitlist: 'Pridruži se Listi', darkMode: 'Tamni Način', lightMode: 'Svijetli Način', language: 'Jezik' }, dashboard: { home: 'Početna', search: 'Traži', music: 'Glazba', library: 'Knjižnica', favorites: 'Favoriti', leaderboard: 'Ljestvica', profile: 'Profil', wallet: 'Novčanik', chat: 'Chat', learning: 'Učenje', market: 'Tržište', ai: 'AI', ads: 'Oglasi', artist: 'Studio', moderator: 'Moderator', admin: 'Admin', settings: 'Postavke', logout: 'Odjava', upload: 'Prijenos', earnings: 'Zarada', followers: 'Pratitelji', streams: 'Slušanja', likes: 'Sviđanja' } },
  sr: { nav: { home: 'Почетна', discover: 'Откриј', artists: 'За Уметнике', marketplace: 'За Бизнис', community: 'За Заједницу', business: 'За Бизнис', login: 'Пријава', signup: 'Регистрација', getStarted: 'Почни' }, hero: { title: 'Будућност', titleHighlight: 'Музике је Децентрализована', subtitle: 'Слушај, зарађуј и поседуј своју музику. Thundra Music даје уметницима 65% тантијема.', cta: 'Почни Слушати', secondaryCta: 'Сазнај Више', stats: { artists: 'Тантијеме Уметника', royalties: 'Више од Spotifyja', fans: 'Активни Фанови', burned: '$THDR Спаљено' } }, features: { title: 'Све Што Музика Треба Бити', subtitle: 'Комплетан екосистем за уметнике, фанове и креаторе', streaming: { title: 'Плаћено Слушање', description: 'Заради $THDR за свако слушање.' }, social: { title: 'Друштвени Простори', description: 'Feed, chatovi i audio prostori.' }, marketplace: { title: 'NFT Тржиште', description: 'Музички NFT-ови, карте и роба.' }, ai: { title: 'AI Алати', description: 'Ствари музику са AI.' }, governance: { title: 'Управљање', description: 'Гласај за одлуке.' }, wallet: { title: 'Новчаник', description: 'Сачувај $THDR и NFT.' } }, tokenomics: { title: '$THDR Tokenomics', subtitle: 'Праведна дистрибуција.', artistRoyalties: 'Тантијеме', fanRewards: 'Награде', platform: 'Платформа', burning: '100% Накнада Спаљено' }, footer: { tagline: 'Децентрализована Музичка Инфраструктура За Будућност.', company: 'Компанија', resources: 'Ресурси', legal: 'Правно', social: 'Друштвено', copyright: '© 2026 Thundra Music Inc. Сва права задржана.', quickLinks: 'Брзе Везе' }, common: { learnMore: 'Сазнај Више', comingSoon: 'Ускоро', joinWaitlist: 'Придружи се Листи', darkMode: 'Тамни Режим', lightMode: 'Светли Режим', language: 'Језик' }, dashboard: { home: 'Почетна', search: 'Тражи', music: 'Музика', library: 'Библиотека', favorites: 'Фаворити', leaderboard: 'Лествица', profile: 'Профил', wallet: 'Новчаник', chat: 'Chat', learning: 'Учење', market: 'Тржиште', ai: 'AI', ads: 'Огласи', artist: 'Студио', moderator: 'Модератор', admin: 'Админ', settings: 'Подешавања', logout: 'Одјава', upload: 'Отпреми', earnings: 'Зарада', followers: 'Пратиоци', streams: 'Слушања', likes: 'Свиђања' } },
  da: { nav: { home: 'Hjem', discover: 'Opdag', artists: 'For Kunstnere', marketplace: 'For Virksomheder', community: 'For Fællesskab', business: 'For Virksomheder', login: 'Log ind', signup: 'Tilmeld', getStarted: 'Kom i gang' }, hero: { title: 'Fremtiden for', titleHighlight: 'Musik er Decentraliseret', subtitle: 'Stream, tjen og ej din musik. Thundra Music giver kunstnere 65% royalties.', cta: 'Begynd at Lytte', secondaryCta: 'Lær Mere', stats: { artists: 'Kunstner Royalties', royalties: 'Højere end Spotify', fans: 'Aktive Fans', burned: '$THDR Brændt' } }, features: { title: 'Alt Hvad Musik Bør Være', subtitle: 'Et komplet økosystem for kunstnere, fans og skabere', streaming: { title: 'Betalt Streaming', description: 'Tjen $THDR for hver stream.' }, social: { title: 'Sociale Rum', description: 'Feed, chats og audio spaces.' }, marketplace: { title: 'NFT Markedsplads', description: 'Musik NFTs, billetter og merchandise.' }, ai: { title: 'AI Værktøjer', description: 'Skab musik med AI.' }, governance: { title: 'Styring', description: 'Stem om beslutninger.' }, wallet: { title: 'Pung', description: 'Opbevar $THDR og NFT.' } }, tokenomics: { title: '$THDR Tokenomics', subtitle: 'Retfærdig fordeling.', artistRoyalties: 'Royalties', fanRewards: 'Belønninger', platform: 'Platform', burning: '100% Gebyrer Brændt' }, footer: { tagline: 'Den Decentraliserede Musikinfrastruktur For Fremtiden.', company: 'Virksomhed', resources: 'Ressourcer', legal: 'Juridisk', social: 'Socialt', copyright: '© 2026 Thundra Music Inc. Alle rettigheder forbeholdes.', quickLinks: 'Hurtige Links' }, common: { learnMore: 'Lær Mere', comingSoon: 'Kommer Snart', joinWaitlist: 'Tilmeld Venteliste', darkMode: 'Mørk Tilstand', lightMode: 'Lys Tilstand', language: 'Sprog' }, dashboard: { home: 'Hjem', search: 'Søg', music: 'Musik', library: 'Bibliotek', favorites: 'Favoritter', leaderboard: 'Rangliste', profile: 'Profil', wallet: 'Pung', chat: 'Chat', learning: 'Læring', market: 'Marked', ai: 'AI', ads: 'Annoncer', artist: 'Studio', moderator: 'Moderator', admin: 'Admin', settings: 'Indstillinger', logout: 'Log ud', upload: 'Upload', earnings: 'Indtjening', followers: 'Følgere', streams: 'Streams', likes: 'Likes' } },
  sv: { nav: { home: 'Hem', discover: 'Upptäck', artists: 'För Artister', marketplace: 'För Företag', community: 'För Gemenskap', business: 'För Företag', login: 'Logga in', signup: 'Registrera', getStarted: 'Kom igång' }, hero: { title: 'Framtiden för', titleHighlight: 'Musik är Decentraliserad', subtitle: 'Streama, tjäna och äg din musik. Thundra Music ger artister 65% royalties.', cta: 'Börja Lyssna', secondaryCta: 'Läs Mer', stats: { artists: 'Artist Royalties', royalties: 'Högre än Spotify', fans: 'Aktiva Fans', burned: '$THDR Bränd' } }, features: { title: 'Allt Musik Bör Vara', subtitle: 'Ett komplett ekosystem för artister, fans och skapare', streaming: { title: 'Betald Streaming', description: 'Tjäna $THDR för varje stream.' }, social: { title: 'Sociala Utrymmen', description: 'Flöde, chattar och ljudutrymmen.' }, marketplace: { title: 'NFT Marknadsplats', description: 'Musik NFTs, biljetter och merchandise.' }, ai: { title: 'AI Verktyg', description: 'Skapa musik med AI.' }, governance: { title: 'Styrning', description: 'Rösta om beslut.' }, wallet: { title: 'Plånbok', description: 'Lagra $THDR och NFT.' } }, tokenomics: { title: '$THDR Tokenomics', subtitle: 'Rättvis fördelning.', artistRoyalties: 'Royalties', fanRewards: 'Belöningar', platform: 'Plattform', burning: '100% Avgifter Brända' }, footer: { tagline: 'Den Decentraliserade Musikinfrastrukturen För Framtiden.', company: 'Företag', resources: 'Resurser', legal: 'Juridiskt', social: 'Socialt', copyright: '© 2026 Thundra Music Inc. Alla rättigheter förbehållna.', quickLinks: 'Snabblänkar' }, common: { learnMore: 'Läs Mer', comingSoon: 'Kommer Snart', joinWaitlist: 'Gå med i Väntelistan', darkMode: 'Mörkt Läge', lightMode: 'Ljust Läge', language: 'Språk' }, dashboard: { home: 'Hem', search: 'Sök', music: 'Musik', library: 'Bibliotek', favorites: 'Favoriter', leaderboard: 'Topplista', profile: 'Profil', wallet: 'Plånbok', chat: 'Chatt', learning: 'Lärande', market: 'Marknad', ai: 'AI', ads: 'Annonser', artist: 'Studio', moderator: 'Moderator', admin: 'Admin', settings: 'Inställningar', logout: 'Logga ut', upload: 'Ladda upp', earnings: 'Intäkter', followers: 'Följare', streams: 'Streams', likes: 'Gillar' } },
  no: { nav: { home: 'Hjem', discover: 'Oppdag', artists: 'For Artister', marketplace: 'For Bedrifter', community: 'For Fellesskap', business: 'For Bedrifter', login: 'Logg inn', signup: 'Registrer', getStarted: 'Kom i gang' }, hero: { title: 'Fremtiden for', titleHighlight: 'Musikk er Desentralisert', subtitle: 'Stream, tjen og eie musikken din. Thundra Music gir artister 65% royalties.', cta: 'Begynn å Lytte', secondaryCta: 'Lær Mer', stats: { artists: 'Artist Royalties', royalties: 'Høyere enn Spotify', fans: 'Aktive Fans', burned: '$THDR Brent' } }, features: { title: 'Alt Musikk Bør Være', subtitle: 'Et komplett økosystem for artister, fans og skapere', streaming: { title: 'Betalt Streaming', description: 'Tjen $THDR for hver stream.' }, social: { title: 'Sosiale Rom', description: 'Feed, chatter og lydrom.' }, marketplace: { title: 'NFT Markedsplass', description: 'Musikk NFTs, billetter og merchandise.' }, ai: { title: 'AI Verktøy', description: 'Lag musikk med AI.' }, governance: { title: 'Styring', description: 'Stem om avgjørelser.' }, wallet: { title: 'Lommebok', description: 'Lagre $THDR og NFT.' } }, tokenomics: { title: '$THDR Tokenomics', subtitle: 'Rettferdig fordeling.', artistRoyalties: 'Royalties', fanRewards: 'Belønninger', platform: 'Plattform', burning: '100% Gebyrer Brent' }, footer: { tagline: 'Den Desentraliserte Musikkinfrastrukturen For Fremtiden.', company: 'Selskap', resources: 'Ressurser', legal: 'Juridisk', social: 'Sosialt', copyright: '© 2026 Thundra Music Inc. Alle rettigheter reservert.', quickLinks: 'Hurtiglenker' }, common: { learnMore: 'Lær Mer', comingSoon: 'Kommer Snart', joinWaitlist: 'Bli med på Ventelisten', darkMode: 'Mørk Modus', lightMode: 'Lys Modus', language: 'Språk' }, dashboard: { home: 'Hjem', search: 'Søk', music: 'Musikk', library: 'Bibliotek', favorites: 'Favoritter', leaderboard: 'Toppliste', profile: 'Profil', wallet: 'Lommebok', chat: 'Chat', learning: 'Læring', market: 'Marked', ai: 'AI', ads: 'Annonser', artist: 'Studio', moderator: 'Moderator', admin: 'Admin', settings: 'Innstillinger', logout: 'Logg ut', upload: 'Last opp', earnings: 'Inntekter', followers: 'Følgere', streams: 'Streams', likes: 'Liker' } },
  fi: { nav: { home: 'Koti', discover: 'Löydä', artists: 'Artisteille', marketplace: 'Yrityksille', community: 'Yhteisölle', business: 'Yrityksille', login: 'Kirjaudu', signup: 'Rekisteröidy', getStarted: 'Aloita' }, hero: { title: 'Musiikin Tulevaisuus', titleHighlight: 'On Hajautettu', subtitle: 'Striimaa, ansaitse ja omista musiikkisi. Thundra Music antaa artisteille 65% rojaltit.', cta: 'Aloita Kuuntelu', secondaryCta: 'Lue Lisää', stats: { artists: 'Artistien Rojaltit', royalties: 'Korkeampi kuin Spotify', fans: 'Aktiiviset Fanit', burned: '$THDR Poltettu' } }, features: { title: 'Kaikki Mitä Musiikin Pitäisi Olla', subtitle: 'Täydellinen ekosysteemi artisteille, faneille ja luojille', streaming: { title: 'Maksullinen Striimaus', description: 'Ansaitse $THDR jokaisesta striimauksesta.' }, social: { title: 'Sosiaaliset Tilat', description: 'Feed, chatit ja äänitilat.' }, marketplace: { title: 'NFT Markkinapaikka', description: 'Musiikki NFT:t, liput ja merchandise.' }, ai: { title: 'AI Työkalut', description: 'Luo musiikkia AI:lla.' }, governance: { title: 'Hallinto', description: 'Äänestä päätöksistä.' }, wallet: { title: 'Lompakko', description: 'Säilytä $THDR ja NFT.' } }, tokenomics: { title: '$THDR Tokenomics', subtitle: 'Reilu jakelu.', artistRoyalties: 'Rojaltit', fanRewards: 'Palkinnot', platform: 'Alusta', burning: '100% Maksuista Poltettu' }, footer: { tagline: 'Hajautettu Musiikki-Infrastruktuuri Tulevaisuudelle.', company: 'Yritys', resources: 'Resurssit', legal: 'Oikeudellinen', social: 'Sosiaalinen', copyright: '© 2026 Thundra Music Inc. Kaikki oikeudet pidätetään.', quickLinks: 'Pikalinkit' }, common: { learnMore: 'Lue Lisää', comingSoon: 'Tulossa Pian', joinWaitlist: 'Liity Odotuslistalle', darkMode: 'Tumma Tila', lightMode: 'Vaalea Tila', language: 'Kieli' }, dashboard: { home: 'Koti', search: 'Hae', music: 'Musiikki', library: 'Kirjasto', favorites: 'Suosikit', leaderboard: 'Johtolista', profile: 'Profiili', wallet: 'Lompakko', chat: 'Chat', learning: 'Oppiminen', market: 'Markkinat', ai: 'AI', ads: 'Mainokset', artist: 'Studio', moderator: 'Moderaattori', admin: 'Admin', settings: 'Asetukset', logout: 'Kirjaudu ulos', upload: 'Lataa', earnings: 'Ansiot', followers: 'Seuraajat', streams: 'Striimit', likes: 'Tykkäykset' } },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>(() => {
    const stored = localStorage.getItem('thundra-language');
    return (stored as LanguageCode) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('thundra-language', language);
  }, [language]);

  // Merge footer translations with defaults for missing keys
  const baseTranslation = translations[language] || translations.en;
  const defaultFooter = enTranslations.footer;
  const t: Translations = {
    ...baseTranslation,
    footer: {
      ...defaultFooter,
      ...baseTranslation.footer,
    } as FooterTranslations,
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
